export const SET_SHOW_BTN = 'SET_SHOW_BTN'
export const GET_TOKEN = 'GET_TOKEN'
export const POST_REGISTER = 'POST_REGISTER'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_ALL_USER = 'GET_ALL_USER'
export const GET_USER_INFO = 'GET_USER_INFO'
